#+TITLE: basemacs
An Emacs base to build on.

* About
=basemacs= is the (mostly) unopinionated start to an Emacs configuration -- a *base* to build on. It contains some sane defaults and uses a minimal set of packages to get you started with your own config.

All configuration is done in =org= files that are tangled to =elisp=. Further configuration can be done using =org= files, or by editing =elisp= files directly.

=basemacs= is meant to be simple, so fork it and hack away!

If you want to know a little bit more about why I created this project, see this [[https://kwpav.github.io/posts/emacs_refinancing/][blog post]].

** Packages Used
=basemacs= uses a small set of packages to get started.

- [[https://github.com/raxod502/straight.el][straight.el]] - package management
- [[https://github.com/jwiegley/use-package][use-package]] - package configuration
- [[https://github.com/noctuid/general.el][general.el]] - configuring custom keys and hooks
- [[https://github.com/justbur/emacs-which-key][which-key]] - display key combos
- [[https://github.com/joaotavora/yasnippet][yasnippet]] - code snippets

* Requirements
The only requirements are:
- Emacs 27+

I have only tested it on OSX and Linux, but it should have no problems working in other environments.

* Using
** Install
The easiest way to get started is to fork this repository and use it as the start of your own configuration. There should be no real need to keep track of updates.

After that, there are a few ways of using this:

1. Backup your current config and clone this into =~/.emacs.d= or =~/.config/emacs=
After you backup your current config, clone this repo to =~/.emacs.d=:
#+begin_src sh
  git clone https://github.com/<user>/basemacs.git ~/.emacs.d
#+end_src

Or to =~/.config/emacs=:
#+begin_src sh
  git clone https://github.com/<user>/basemacs.git ~/.config/emacs
#+end_src

2. OR clone this repo to your preferred location and use [[https://github.com/plexus/chemacs][chemacs]]
For example,  clone this repo to =~/.config/basemacs=:
#+begin_src sh
  git clone https://github.com/<user>/basemacs.git ~/.config/basemacs
#+end_src

Then add the cloned location to =~/.emacs-profiles.el=:
#+begin_src emacs-lisp
  (("default" . ((user-emacs-directory . "~/.emacs.d")))
   ("basemacs" . ((user-emacs-directory . "~/config/basemacs"))))
#+end_src

Run with =emacs --with-profile basemacs=.

3. OR you can just copy/paste whatever bits and pieces of this you want to your own config

** First Steps
Now that the config is in the right place, simply start up Emacs! The first time may take a little while as packages install, but subsequent startups will be much faster.

[[file:config.org][config.org]] contains a starting configuration for =init.el=. Configuration can either be done by using that file, or editing =init.el= directly.

** Next Steps
Ok, we've got a basic config, now what? Check out the [[file:modules.org][modules]]! This contains a set of modules for =basemacs= that provide some extra features, such as: narrowing/completion frameworks (=helm=, =ivy=, etc.), making things look a little nicer with some themes, =vim= emulation, and more!

You can also check out [[file:base.org][basemacs-core.org]] which contains the =basemacs= setup and modify that if you find something you don't like. (Don't forget to tangle it!)

* FAQ
** What is the difference between =basemacs= and all the other Emacs distros/starters out there?
=basemacs= is intented to be smaller and simpler than the others (with the exception of maybe =yay-evil=.) There are no "batteries" included (well, other than =magit= perhaps!). =basemacs= is meant as a starting point for an Emacs configuration, it can easily be modified to fit a users needs as there is no magic going on here.

* Inspired By
This project was inspired by all these other great Emacs starter kits/configurations/distributions/whatever you want to call them:
- [[https://github.com/ianpan870102/yay-evil-emacs][yay-evil-emacs]]
- [[https://github.com/MatthewZMD/.emacs.d][M-EMACS]]
- [[https://github.com/hlissner/doom-emacs][doom-emacs]]
- [[https://www.spacemacs.org/][Spacemacs]]
- [[https://github.com/bbatsov/prelude][Prelude]]
- [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]]
